project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - about.qmd
  - practical1_compiler.qmd
  - slides/slides_1.qmd
website:
  title: Troms√∏ workshop 2025
  navbar:
    logo: INLA_logo.png
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: Slides
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.html
        text: Home
      - section: "Slides"
        contents: 
         - href: slides/slides_1.html
           text: Lecture 
      - section: "Practicals"
        contents:
         - href: practical1_compiler.qmd
           text: "Practical 1"
  page-navigation: true
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
