name: Publish Quarto Websites

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render copenhagen_ices
        working-directory: workshop_materials/copenhagen_ices
        run: quarto render

#      - name: Render BES_workshop
#        working-directory: workshop_materials/BES_workshop
#        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workshop_materials
